# This is a basic workflow to help you get started with Actions

name: yuka-case

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
    - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # The "build" workflow
  build:  
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
  
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Create .env file
    - name: create env file
      uses: SpicyPizza/create-envfile@v1.3
      with:
        envkey_APP_URL: ${{ secrets.APP_URL }}
        envkey_APP_NAME: ${{ secrets.APP_NAME }}
        envkey_APP_DEBUG: ${{ secrets.APP_DEBUG }}
        envkey_APP_PORT: ${{ secrets.APP_PORT }}
        envkey_SYSTEM_USERNAME : ${{ secrets.SYSTEM_USERNAME }}
        envkey_SYSTEM_PASSWORD : ${{ secrets.SYSTEM_PASSWORD }}
        envkey_DB_HOST: ${{ secrets.DB_HOST }}
        envkey_DB_NAME: ${{ secrets.DB_NAME }}
        envkey_DB_USER: ${{ secrets.DB_USER }}
        envkey_DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        envkey_DB_PORT: ${{ secrets.DB_PORT }}
        directory: './'
        file_name: '.env'
        fail_on_empty: false
      
    - name: Run vet
      run: go vet .

    # Run build of the application
    - name: Run build
      run: go build . 